apiVersion: v1
kind: Secret
metadata:
  name: central-kms-secret
  labels:
      app: central-kms
type: Opaque
data:
  # base64 encoded string
  db.username: a21z
  # base64 encoded string
  db.password: a21z
